---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: stop instance by instance id
      ec2:
         instance_ids: i-8fa87a06
         state: running
         wait: yes
         region: us-east-1
      register: ec2
