---
- hosts: localhost
  connection: local
  gather_facts: no


  tasks:
    - name: Creating Security group in VPC
      ec2_group:
        name: SSH-SG
        description: Allow only ssh from anywhere
        vpc_id: vpc-4a3ce52e
        region: us-east-1
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0