
---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: Provision a set of instances
      ec2:
         key_name: virginia
         group: launch-wizard-2
         region: us-east-1
         instance_type: t1.micro
         image: ami-8997afe0
         vpc_subnet_id: subnet-1edec669
         wait: true
         exact_count: 1
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
      register: ec2